### ISSUE TITLE
Question: Difference between DTWG and UDT?

### ISSUE THREAD

**Issue by justrhysism** [design-tokens/working-group#5]
Hi, I'm curious as to the differences between this WG and the goals of [UDT](https://github.com/universal-design-tokens/udt) (whom is referenced as inspiration)?

The reason I ask is if two parties are moving in slightly different directions it could begin n+1 design token specs.

Whatever the outcome - a universal standard of design token which is software/platform agnostic is absolutely what we should be moving towards.

**Comment by c1rrus** [comment]
Good question. I'm the guy behind UDT, so I'll have a go at answering this from my side: I think we have the same goal, i.e.:

>a universal standard of design token which is software/platform agnostic

But, even though I started UDT some time ago, it's mostly been me noodling around in my spare time and is still way off being complete enough for production.

While it's been publicly visible from the start, I  intentionally kept relatively quiet about it so far. I wanted to have something tangible before I actively sought feedback and contributions. (I have lots of ideas in my head but haven'got them written down or prototyped yet)

Then, last week, I was mentioned in a Twitter thread discussing a universal design token format (thanks @sturobson!): https://twitter.com/pixelbeat/status/1141888413156745217?s=19

So, I got involved! I've been following and contributing to the RFC discussions in issue #1. I'm genuinely pleased to see all the interest and debate here. Whatever happens next, at least I now know I wasn't the only person longing for a universal design token format.

@kaelig, who kicked off this DTWG also got in touch with me separately. We haven't gotten around to a call yet, but will hopefully do so soon.

Personally, I'd like to avoid ending up with rival design token standards. So, I'd be quite happy to merge UDT with DTWG if everyone else was willing. Perhaps "Universal Design Tokens" could be the name for whatever file format this WG comes up with. In any case, my only wish is to continue to be involved and help create a standard we can all use.

That's my 2¢ anyway. I'd love to hear what everyone else thinks :-)

https://xkcd.com/927/

**Comment by kaelig** [comment]
Thank you for asking, I can see how it could be confusing and reason for concerns.

The Design Tokens Working Group is about getting everyone to sit at the same table and see if we can find a common way to reason about concepts that keep being re-invented over and over. Just like the W3C is getting browser vendors, companies, and individuals to sit around the same table.

For that to happen, I believe we need to start again from the beginning, and hear what tool vendors have to say, with a heavy bias towards seeing adoption in those tools.

@hypd and I have reached out to numerous companies who build tools, and we're hoping to see them being officially represented on the working group very soon, bringing their expertise to the table, watch this space!

PS: eventually, I could see Theo's spec, Style Dictionary's spec, UDT, and System UI build atop of the spec that comes out of this working group, or at least being able to consume this format.

**Comment by kaelig** [comment]
Closing this, but leaving the conversation open for comments in case further questions come up.
