### ISSUE TITLE
Question: contact details in README?

### ISSUE THREAD

**Issue by bomberstudios** [design-tokens/working-group#7]
Currently we don’t publish contact details for companies / individuals in the README. Is this intentional because we assume all communications will happen on GitHub?

And if it isn’t, do we think it would be a Good Thing™ to have public contact details there?

**Comment by kaelig** [comment]
This is a very good question. It’s not intentional, and more of a list I put together very quickly.

I’m partial to referencing GitHub usernames next to company/project names, rather than using email. What do you think?

**Comment by sturobson** [comment]
I think GitHub usernames is more appropriate for now - as the discussions are on Github. Having personal/work emails could potentially move conversations outside of the various working groups. Which would not be an easy thing to track.

**Comment by kaelig** [comment]
Closing this for now – a full list of individual members and company representatives will be put together soon.
